version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci --cache .npm --prefer-offline
    build:
      commands:
        commands:
          - echo "ACCESS_KEY_ID=$ACCESS_KEY_ID" >> .env.production
          - echo "BUCKET_NAME=$BUCKET_NAME" >> .env.production
          - echo "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> .env.production
          - echo "REGION=$REGION" >> .env.production
          - env | grep -e NEXT_PUBLIC_ >> .env.production
          - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - .next/cache/**/*
      - .npm/**/*
