version: 1
frontend:
 phases:
   preBuild:
     commands:
       - npm ci
   build:
     commands:
       - echo "ACCESS_KEY_ID=$ACCESS_KEY_ID" >> .env.production
       - echo "BUCKET_NAME=$BUCKET_NAME" >> .env.production
       - echo "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> .env.production
       - echo "REGION=$REGION" >> .env.production
       - env | grep -e NEXT_PUBLIC_ >> .env.production
       - npm run build
 artifacts:
   baseDirectory: .next
   files:
     - '**/*'
 cache:
   paths:
     - node_modules/**/*
     - .next/cache/**/*